# Generated by Django 2.0.7 on 2019-04-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_a', models.CharField(blank=True, max_length=40)),
                ('city_b', models.CharField(blank=True, max_length=40)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('petrol_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('car_consumption', models.DecimalField(decimal_places=2, max_digits=4)),
                ('journey_cost', models.FloatField()),
            ],
        ),
    ]
